### ISSUE TITLE
Crash relating to fallen tree features?

### ISSUE THREAD

**Issue by CrystalZink** [TunefulTurnip/Deep-Aether#140] opened 2024-01-11 15:22 UTC
No clue what happened here, suspected mod seems to be Deep Aether, was just flying around the dimension & a crash happened (as in a black loading screen that forced me to kill the instance)

https://mclo.gs/mkfHEBt

**Comment by TunefulTurnip** [comment] 2024-01-11 21:23
Duplicate of #138

**Closed as not planned by TunefulTurnip** 2024-01-11 21:23 UTC
