### ISSUE TITLE
[1.20.1] Creative flight no longer works when this mod is present

### ISSUE THREAD

**Issue by jinkhya** [TunefulTurnip/Deep-Aether#100] opened 2023-09-25 14:14 UTC
Hello,
For some reason creative flight no longer works with deep aether.

To test it 
- make an instance with 
```
aeroblender-1.20.1-1.0-neoforge.jar
aether-1.20.1-1.0.0-beta.1.2-neoforge.jar
deep_aether-1.20.1-1.0.9.jar
geckolib-forge-1.20.1-4.2.3.jar
RingsOfAscension-1.20.1-2.0.1.jar (to test flying with the ring)
TerraBlender-forge-1.20.1-3.0.0.169.jar
```
- equip the ring of flight
- double jump to try to fly
- do the same without Deep aether and it should now work

I put rings of ascension coz it's easy enough to test with the flying ring but it breaks any kind of creative flight like angel ring, ars nouveau flight tablet etc.

Thanks in advance,
Jin

**Comment by darksonic300** [comment] 2023-09-25 14:21
An issue already resolved with the upcoming fixes. Caused by how Chromatic Aerclouds were coded.

**Closed as completed by darksonic300** 2023-09-25 14:21 UTC
